[package]

name = "gravity"
version = "0.0.1"
authors = ["Emilia Bopp <Emilia.bopp@aepsil0n.de>"]

[dependencies.acacia]
git = "https://github.com/aepsil0n/acacia.git"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra.git"
